add convertor test
amandadumi/qmcpack pull request #15
Opened 2024-01-16 01:11 UTC by shivupa

This adds a test

2024-01-16 02:53 UTC, amandadumi requested changes
This is perfect, thanks for adding it. Just a few questions. If you don't have bandwidith i can just approve and remove them myself, but wanted to be sure they weren't intentional.

2024-01-16 02:53 UTC, amandadumi commented on tests/converter/test_LiH_MSD_pyscf/cmd_args.txt
Does this empty file need to be here?

2024-01-16 02:53 UTC, amandadumi commented on tests/converter/test_LiH_MSD_pyscf/gold.wfnoj.xml
why are these named gold?

2024-01-16 03:11 UTC, shivupa commented on tests/converter/test_LiH_MSD_pyscf/gold.wfnoj.xml
idk it seemed like all the reference values are called gold? I guess like gold standard? Sorta confusing imo

2024-01-16 03:11 UTC, shivupa commented on tests/converter/test_LiH_MSD_pyscf/cmd_args.txt
not sure but its in the other pyscf test lol

2024-01-22 21:22 UTC, amandadumi commented
looks good thank you!

2024-01-22 21:22 UTC, merged